#!/bin/bash

db_user=drupal
db_name=drupal
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting drupal domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/drupal
sudo rm -f /etc/nginx/conf.d/$domain.d/drupal.conf
